In [ ]:
import numpy as np
my_list = list(range(100000))
my_array = np.array(100000)
print(my_list)
print(my_array)

In [17]:
%time for _ in range(10): [i*2 for i in my_list]

CPU times: total: 46.9 ms
Wall time: 51.8 ms


In [18]:
%time for _ in range(10): my_array * 2

CPU times: total: 0 ns
Wall time: 216 µs


In [8]:
data = [1,23,343,4,34]
tup = (12,12,12,234)
array = np.array(data)
tuple1 = np.array(tup)

In [10]:
print(data)
print(array)
print(tuple1)
array.ndim # arrayning o'lchamini chiqaradi

[1, 23, 343, 4, 34]
[  1  23 343   4  34]
[ 12  12  12 234]


1

In [14]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
num_matrix = np.array(matrix)
num_matrix
num_matrix.ndim # massiv ning o'lchami
num_matrix.shape # qator va ustunlar soni
num_matrix.size # massivdagi jami elementlar soni

9

In [19]:
array1 = np.ones(shape=(4,5))
array1
array2 = np.zeros(shape=(3,4))
array2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
array3 = np.arange(2,30,3)
array3

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [26]:
arr = np.array([1,2,3,4],dtype=np.float64)
arr1 = np.array([1,2,3,4],dtype=np.int16)
arr1
arr1.dtype

dtype('int16')

In [28]:
nums = np.array([1,2,3,4],dtype=np.float32)
float_num = nums.astype(np.int16)
float_num

array([1, 2, 3, 4], dtype=int16)

In [29]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[1:4])

[15 20 25]
