1.Numpy kutubxonasini versiyasini tekshirish

In [1]:
import numpy as np
print(np.__version__)

1.26.2


2. 1D array yaratish

In [3]:
array1 = np.arange(0,10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. Boolean array yaratish

In [7]:
bool_array = np.full((3,3),False,dtype=bool)
bool_array

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

4.Arraydai toq elementlarni chiqarish

In [10]:
array2 = np.arange(0,10)
result = np.where(array2 % 2 == 1)

result1 = array2[array2 % 2 == 1]
result1

array([1, 3, 5, 7, 9])

5. Toq indexdagi elementlarni boshqa elementlar bilan almashtirish

In [42]:
array3 = np.arange(0,7)
result3 = np.where(array3 % 2 == 1,-1,array3)
result3

array([ 0, -1,  2, -1,  4, -1,  6])

6. 1D arrayni  2D arrayga almashtirish 

In [54]:
array5 = np.arange(0,12)

array6 = array5.reshape((4,3))

array6

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

7. 2 ta vertikal array stack qurish

In [60]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)

np.concatenate([a,b],axis=0)

np.vstack([a,b])

np.r_[a,b]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

8. 2 ta gorizontal array stack qurish

In [65]:
np.concatenate([a,b],axis=1)
np.hstack([a,b])
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

9. a va b arrayning umumiy elementlarini olish

In [67]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

10. a arraydagi  b elementlari bor elementlarni o'chirish

In [69]:
np.setdiff1d(b,a)

array([ 7,  8,  9, 10])